version: "3.9"

services:
    db:
        image: postgres:latest
        container_name: vpn-control-postgres
        restart: always
        volumes:
            - pg-data-postgres:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_DATABASE}"
        networks:
            - vpn-core-internal-net
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
            interval: 10s
            timeout: 5s
            retries: 5

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - "8002:8080"
        depends_on:
            db:
                condition: service_healthy
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            - vpn-core-internal-net
            - vpn-core-public-net

    app:
        image: elyerr/vpn-control:latest
        container_name: vpn-control
        ports:
            - "8001:80"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .env:/var/www/.env
        command: sh -c "/usr/local/bin/laravel-scripts.sh"
        networks:
            - vpn-core-internal-net
            - vpn-core-public-net

volumes:
    pg-data-postgres:

networks:
    vpn-core-internal-net:
        internal: true
    vpn-core-public-net:
        driver: bridge
