version: "3.9"

services:
    app:
        image: elyerr/vpn-control:latest
        container_name: vpn-control
        ports:
            - "8001:80"
        depends_on:
            - db
        volumes:
            - .env:/var/www/.env
        command: sh -c "/usr/local/bin/laravel-scripts.sh"
        networks:
            - vpn_core_public_net
            - vpn_core_internal_net

    db:
        image: postgres:latest
        container_name: vpn-control-postgres
        restart: always
        volumes:
            - pg-data:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_DATABASE}"
        networks:
            - vpn_core_internal_net 

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - "8002:8080"
        depends_on:
            - db
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            - vpn_core_public_net
            - vpn_core_internal_net

volumes:
    pg-data:

networks:
    vpn_core_internal_net:
        internal: true
    vpn_core_public_net:
        driver: bridge
